runtime: php55
api_version: 1

runtime_config:
    document_root: .

handlers:
- url: /
  script: index.php

- url: /index\.html
  script: index.php

- url: /scss
  static_dir: scss

- url: /css
  static_dir: css

- url: /libs
  static_dir: libs
  



- url: /.*
  script: not_found.php

  env_variables:
    CLOUDSQL_HOST: mysql:unix_socket=/cloudsql/cloud-project-siit:asia-southeast1:siit-cloud
    CLOUDSQL_USER: "root"
    CLOUDSQL_DB: "inventary"
    CLOUDSQL_PASSWORD: " " 
    CLOUDSQL_DNS: "/cloudsql/cloud-project-siit:asia-southeast1:siit-cloud"