runtime: php55
api_version: 1
runtime_config:
  document_root: Siit-cloud-project
handlers:
- url: /scss
  static_dir: scss
- url: /css
  static_dir: css
- url: /libs
  static_dir: libs
- url: /vendor
  static_dir: vendor
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /
  script: index.php
- url: /index.php
  script: index.php
- url: /logout
  script: logout.php
- url: /login.php
  script: login.php
- url: /carts.php
  script: carts.php
- url: /tables.php
  script: tables.php
- url: /generate_pdf.php
  script: generate_pdf.php
- url: /reorder.php
  script: reorder.php
env_variables:
  CLOUDSQL_USER: "root"
  CLOUDSQL_DB: "inventary"
  CLOUDSQL_PASSWORD: " " 
  CLOUDSQL_DNS: "/cloudsql/cloud-project-siit:asia-southeast1:siit-cloud"
